"use client";

import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowLeft, ArrowRight, BadgeDollarSign, Bell, Bot, Building2, Check, ChevronDown, ChevronRight, Database, FileCheck2, FileText, Filter, Gauge, Home, LayoutDashboard, Menu, MessageSquareText, MoreHorizontal, PanelLeftClose, Receipt, Search, Send, Settings, ShieldCheck, Sparkles, Upload, Users, X, Zap } from "lucide-react";
import { aiAnswers, contracts, findings, integrityTrend, invoices, primaryFindings, revenueTrend, type Finding } from "@/lib/data";
import { Logo } from "./logo";

type Page = "Overview"|"Revenue Audit"|"Customers"|"Contracts"|"Usage"|"Billing"|"Findings"|"AI Investigator"|"Data Sources";
const nav: [Page, React.ElementType][] = [["Overview",LayoutDashboard],["Revenue Audit",Gauge],["Customers",Users],["Contracts",FileText],["Usage",Activity],["Billing",Receipt],["Findings",ShieldCheck],["AI Investigator",Bot],["Data Sources",Database]];
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);

export function ProductApp({onExit}:{onExit:()=>void}) {
  const [page,setPage]=useState<Page>("Overview"); const [sidebar,setSidebar]=useState(false); const [customer,setCustomer]=useState<string|null>(null); const [connect,setConnect]=useState(false);
  const go=(p:Page)=>{setPage(p);setCustomer(null);setSidebar(false)};
  return <div className="app-shell">
    <aside className={sidebar?"sidebar open":"sidebar"}><div className="side-logo"><Logo/><button onClick={()=>setSidebar(false)}><PanelLeftClose size={17}/></button></div><div className="workspace"><i>AX</i><span><b>Axiom AI</b><small>Revenue workspace</small></span><ChevronDown size={14}/></div><nav>{nav.map(([label,Icon])=><button className={page===label&&!customer?"active":""} onClick={()=>go(label)} key={label}><Icon size={17}/><span>{label}</span>{label==="Findings"&&<em>7</em>}</button>)}</nav><div className="side-bottom"><button onClick={()=>setConnect(true)}><Zap size={16}/><span>Run on your data</span></button><button><Settings size={16}/><span>Workspace settings</span></button><div className="user"><i>MK</i><span><b>Maya Kim</b><small>VP Finance</small></span><MoreHorizontal size={15}/></div></div></aside>
    <div className="app-main"><header><button className="mobile-menu" onClick={()=>setSidebar(true)}><Menu/></button><div className="breadcrumbs"><button onClick={onExit}><Home size={14}/></button><ChevronRight size={12}/><span>{customer?<>Customers <ChevronRight size={12}/> <b>{customer}</b></>:page}</span></div><div className="header-actions"><span className="period">September 2026 <ChevronDown size={13}/></span><button><Search size={17}/></button><button className="bell"><Bell size={17}/><i/></button><button className="ask" onClick={()=>go("AI Investigator")}><Sparkles size={15}/> Ask RevLeak</button></div></header>
      <main className="app-content">{customer?<CustomerDetail name={customer} back={()=>setCustomer(null)}/>:<PageRouter page={page} setPage={go} openCustomer={setCustomer} openConnect={()=>setConnect(true)}/>}</main>
    </div>{connect&&<ConnectModal close={()=>setConnect(false)} />}
  </div>
}

function PageTitle({eyebrow,title,copy,children}:{eyebrow?:string,title:string,copy:string,children?:React.ReactNode}){return <div className="page-title"> <div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1><p>{copy}</p></div>{children}</div>}
function PageRouter({page,setPage,openCustomer,openConnect}:{page:Page,setPage:(p:Page)=>void,openCustomer:(x:string)=>void,openConnect:()=>void}){
  if(page==="Overview")return <Overview setPage={setPage} openCustomer={openCustomer}/>;
  if(page==="AI Investigator")return <Investigator openCustomer={openCustomer}/>;
  if(page==="Contracts")return <Contracts openCustomer={openCustomer}/>;
  if(page==="Usage")return <Usage/>; if(page==="Billing")return <Billing openCustomer={openCustomer}/>;
  if(page==="Findings"||page==="Revenue Audit")return <Findings title={page} openCustomer={openCustomer}/>;
  if(page==="Customers")return <Customers openCustomer={openCustomer}/>;
  return <DataSources openConnect={openConnect}/>;
}

function Overview({setPage,openCustomer}:{setPage:(p:Page)=>void,openCustomer:(x:string)=>void}){return <>
  <PageTitle eyebrow="SEPTEMBER CLOSE · AUDIT COMPLETE" title="Revenue integrity overview" copy="An independent reconstruction of what Axiom AI should have billed."><button className="outline-btn"><FileCheck2 size={15}/> Export audit</button><button className="solid-btn" onClick={()=>setPage("AI Investigator")}><Sparkles size={15}/> Investigate variance</button></PageTitle>
  <div className="mission"><span><Sparkles size={17}/></span><p><b>Your mission</b>Finance closed September at <strong>$1,080,000</strong>. RevLeak reconstructed <strong>$1,131,420</strong>. Investigate the <em>$51,420 unexplained variance.</em></p><button onClick={()=>setPage("Findings")}>Review findings <ArrowRight size={14}/></button></div>
  <div className="metric-grid"><Metric label="Expected revenue" value="$1,131,420" note="Source-derived calculation"/><Metric label="Billed revenue" value="$1,080,000" note="Stripe + Chargebee"/><Metric alert label="Unexplained variance" value="$51,420" note="4.54% of expected revenue"/><div className="score-card"><div className="ring"><span>95.5<small>%</small></span></div><div><span>REVENUE INTEGRITY SCORE</span><b>Needs attention</b><small>−1.9 pts vs August</small></div></div></div>
  <div className="mini-metrics"><div><span>HIGH-CONFIDENCE LEAKAGE</span><b>$41,280</b><small><i className="green"/> Immediately actionable</small></div><div><span>ACCOUNTS REQUIRING REVIEW</span><b>9</b><small>of 146 customers</small></div><div><span>ANNUALIZED REVENUE AT RISK</span><b>$122K+</b><small>Based on recurring issues</small></div></div>
  <div className="chart-grid"><ChartCard title="Expected vs. billed revenue" subtitle="Last 6 billing periods" legend><ResponsiveContainer width="100%" height={220}><AreaChart data={revenueTrend}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c6df2" stopOpacity={.22}/><stop offset="1" stopColor="#7c6df2" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#22262d" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`$${v/1000}M`} domain={[800,1200]}/><Tooltip content={<RevenueTip/>}/><Area type="monotone" dataKey="expected" stroke="#8b7cf6" strokeWidth={2} fill="url(#rev)"/><Line type="monotone" dataKey="billed" stroke="#69707d" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartCard>
  <ChartCard title="Leakage by root cause" subtitle="$51,420 explained"><ResponsiveContainer width="100%" height={220}><BarChart data={primaryFindings} layout="vertical" margin={{left:5}}><XAxis type="number" hide/><YAxis type="category" dataKey="type" width={105} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="leak" radius={[0,4,4,0]} barSize={18}>{primaryFindings.map((f,i)=><Cell key={f.customer} fill={["#8b7cf6","#34d399","#38bdf8","#fbbf24"][i]}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard></div>
  <div className="chart-grid bottom"><FindingsList openCustomer={openCustomer}/><ChartCard title="Revenue integrity trend" subtitle="Daily score · September"><ResponsiveContainer width="100%" height={210}><LineChart data={integrityTrend}><CartesianGrid stroke="#22262d" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis domain={[94,100]} axisLine={false} tickLine={false}/><Tooltip/><Line type="monotone" dataKey="score" stroke="#34d399" strokeWidth={2.5} dot={{fill:"#0d0f12",stroke:"#34d399",strokeWidth:2}}/></LineChart></ResponsiveContainer></ChartCard></div>
  </>}
function Metric({label,value,note,alert}:{label:string,value:string,note:string,alert?:boolean}){return <div className={alert?"metric alert":"metric"}><span>{label}</span><b>{value}</b><small>{note}</small></div>}
function ChartCard({title,subtitle,legend,children}:{title:string,subtitle:string,legend?:boolean,children:React.ReactNode}){return <section className="chart-card"><div className="card-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{legend&&<span className="chart-legend"><i/>Expected <i/>Billed</span>}<button><MoreHorizontal size={16}/></button></div>{children}</section>}
function RevenueTip({active,payload,label}:any){if(!active||!payload?.length)return null;return <div className="chart-tip"><b>{label} 2026</b>{payload.map((p:any)=><span key={p.name}><i style={{background:p.color}}/>{p.name} <strong>${p.value}K</strong></span>)}</div>}
function FindingsList({openCustomer}:{openCustomer:(x:string)=>void}){return <section className="chart-card findings-list"><div className="card-head"><div><h3>Top findings</h3><p>Prioritized by potential recovery</p></div><button>View all <ArrowRight size={13}/></button></div>{primaryFindings.map(f=><button className="finding-row" key={f.customer} onClick={()=>openCustomer(f.customer)}><Avatar f={f}/><span><b>{f.customer}</b><small>{f.type}</small></span><span className="confidence">{f.confidence}%</span><strong>{money(f.leak)}</strong><ChevronRight size={15}/></button>)}</section>}
function Avatar({f}:{f:Finding}){return <i className="customer-avatar" style={{color:f.color,background:`${f.color}18`,borderColor:`${f.color}30`}}>{f.initials}</i>}

function Investigator({openCustomer}:{openCustomer:(x:string)=>void}){const questions=Object.keys(aiAnswers);const [q,setQ]=useState(questions[0]);const [input,setInput]=useState("");const answer=aiAnswers[q]||aiAnswers[questions[0]];return <div className="investigator"><PageTitle eyebrow="EVIDENCE-GROUNDED AI" title="AI Investigator" copy="Ask questions across every contract, usage event, and invoice."><span className="ai-status"><i/> 9 sources connected</span></PageTitle><div className="chat-layout"><aside><span>SUGGESTED INVESTIGATIONS</span>{questions.map(x=><button className={q===x?"selected":""} key={x} onClick={()=>setQ(x)}><MessageSquareText size={14}/>{x}</button>)}<div className="guardrail"><ShieldCheck size={18}/><b>Evidence-grounded</b><p>Every answer traces back to your source systems. RevLeak never invents financial data.</p></div></aside><section className="chat"><div className="chat-scroll"><div className="user-msg"><i>MK</i><p>{q}</p></div><div className="ai-msg"><span><Sparkles size={16}/></span><div><b>RevLeak AI</b><p>{answer.intro}</p><div className="answer-findings">{answer.rows.map((f,i)=><article key={f.customer}><div className="rank">{i+1}</div><Avatar f={f}/><div><b>{f.customer}<strong>{money(f.leak)}</strong></b><p>{description(f)}</p><button onClick={()=>openCustomer(f.customer)}>Show evidence <ArrowRight size={13}/></button></div></article>)}</div><div className="answer-total"><span><Check size={15}/> Total explained variance</span><b>{money(answer.rows.reduce((a,b)=>a+b.leak,0))}</b></div><small className="answer-meta"><ShieldCheck size={12}/> Answered from 22 source records · Calculations verified</small></div></div></div><form onSubmit={e=>{e.preventDefault();if(input.trim()){setQ(questions.find(x=>x.toLowerCase().includes(input.toLowerCase().split(' ')[0]))||questions[0]);setInput("")}}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about revenue, customers, or a specific discrepancy..."/><button><Send size={16}/></button><small>RevLeak can make mistakes. Verify material decisions against linked evidence.</small></form></section></div></div>}
function description(f:Finding){return f.customer==="Cortex Labs"?"Usage exceeded the 1M-call allowance, but no overage line was added to the Stripe invoice.":f.customer==="Vertex AI"?"A 20% promotional discount expired August 31 but remains active.":f.customer==="Nova Systems"?"240 active seats were detected while only 198 seats were billed.":"The annual 7% contractual uplift was not applied at renewal."}

function CustomerDetail({name,back}:{name:string,back:()=>void}){const f=findings.find(x=>x.customer===name)||findings[0];const cortex=name==="Cortex Labs";const [tab,setTab]=useState("Overview");return <><button className="back-link" onClick={back}><ArrowLeft size={14}/> Back to customers</button><div className="customer-head"><Avatar f={f}/><div><span>CUSTOMER INVESTIGATION</span><h1>{name}</h1><p>Enterprise · Active since Jan 2025 · Salesforce account</p></div><div><button className="outline-btn"><MessageSquareText size={15}/> Ask AI</button><button className="solid-btn">Create recovery task</button></div></div><div className="tabs">{["Overview","Contract","Usage","Billing","Audit Trail"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{cortex?<CortexEvidence tab={tab}/>:<GenericCustomer f={f}/>}</>}
function CortexEvidence({tab}:{tab:string}){return <><div className="customer-kpis"><Metric label="Expected invoice" value="$50,420" note="Contract + observed usage"/><Metric label="Actual invoice" value="$32,000" note="Stripe · INV-02691"/><Metric alert label="Potential leakage" value="$18,420" note="36.5% underbilled"/><div className="confidence-card"><span>CONFIDENCE</span><b>99%</b><small><ShieldCheck size={13}/> Evidence verified</small></div></div><div className="evidence-title"><div><span>REVENUE EXPLANATION</span><h2>{tab==="Overview"?"Why Cortex Labs was flagged":`${tab} evidence`}</h2></div><span className="status-pill">HIGH CONFIDENCE</span></div><div className="evidence-flow"><EvidenceCard icon={FileText} tag="CONTRACT · PAGE 7" title="Commercial terms"><div className="clause">“Usage in excess of <mark>1,000,000 API requests</mark> per calendar month shall be billed at <mark>$0.0045 per additional request.</mark>”</div><button>View source document <ArrowRight size={13}/></button></EvidenceCard><span className="connector"><ChevronRight/></span><EvidenceCard icon={Activity} tag="USAGE API · VERIFIED" title="September consumption"><div className="usage-total"><span>Total API calls</span><b>5,093,333</b></div><div className="meter"><i/><span/></div><div className="meter-labels"><span>1M included</span><strong>4,093,333 overage</strong></div><button>Inspect source events <ArrowRight size={13}/></button></EvidenceCard><span className="connector"><ChevronRight/></span><EvidenceCard icon={Receipt} tag="STRIPE · INV-02691" title="Actual invoice"><div className="invoice-lines"><span>Platform subscription <b>$32,000</b></span><span className="missing">Usage overage <b>Missing</b></span><strong>Total billed <b>$32,000</b></strong></div><button>Open Stripe invoice <ArrowRight size={13}/></button></EvidenceCard></div><div className="calculation"><div><span><Sparkles size={15}/> REVLEAK CALCULATION</span><h3>Expected billing reconstruction</h3></div><div className="formula"><span><small>BASE SUBSCRIPTION</small><b>$32,000</b></span><em>+</em><span><small>4,093,333 EXCESS CALLS × $0.0045</small><b>$18,420</b></span><em>=</em><span><small>EXPECTED INVOICE</small><b>$50,420</b></span><em>−</em><span><small>ACTUAL INVOICE</small><b>$32,000</b></span><em>=</em><span className="leak"><small>LEAKAGE</small><b>$18,420</b></span></div><p><ShieldCheck size={14}/> Root cause: the usage meter was not mapped to an overage line item in Stripe.</p></div></>}
function EvidenceCard({icon:Icon,tag,title,children}:{icon:React.ElementType,tag:string,title:string,children:React.ReactNode}){return <article className="evidence-card"><div className="evidence-head"><span><Icon size={16}/></span><div><small>{tag}</small><b>{title}</b></div><Check size={15}/></div>{children}</article>}
function GenericCustomer({f}:{f:Finding}){return <div className="empty-detail"><Sparkles/><h2>{f.type} identified</h2><p>RevLeak matched contract, usage, and billing records to identify {money(f.leak)} in potential leakage at {f.confidence}% confidence.</p></div>}

function Findings({title,openCustomer}:{title:string,openCustomer:(x:string)=>void}){const [filter,setFilter]=useState("All findings");const shown=filter==="High confidence"?findings.filter(f=>f.confidence>90):findings;return <><PageTitle eyebrow="SEPTEMBER 2026" title={title} copy="Prioritized discrepancies with source-linked evidence."><button className="outline-btn"><Filter size={14}/> Filters</button><button className="solid-btn"><FileCheck2 size={14}/> Export findings</button></PageTitle><div className="filter-row">{["All findings","High confidence","Usage","Pricing","Discounts","Seats","Renewal uplift"].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?"active":""}>{x}{x==="All findings"&&<span>7</span>}</button>)}</div><DataTable heads={["Customer","Leak type","Potential leakage","Confidence","Source systems","Status","Action"]}>{shown.map(f=><tr key={f.customer}><td><button className="customer-cell" onClick={()=>openCustomer(f.customer)}><Avatar f={f}/><b>{f.customer}</b></button></td><td>{f.type}</td><td className="leak-money">{money(f.leak)}</td><td><span className="conf"><i style={{width:`${f.confidence}%`}}/>{f.confidence}%</span></td><td><div className="source-pills">{f.sources.map(s=><span key={s}>{s}</span>)}</div></td><td><span className={`table-status ${f.status.toLowerCase()}`}>{f.status}</span></td><td><button className="table-action" onClick={()=>openCustomer(f.customer)}>Investigate <ChevronRight size={13}/></button></td></tr>)}</DataTable></>}
function DataTable({heads,children}:{heads:string[],children:React.ReactNode}){return <div className="data-table"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Customers({openCustomer}:{openCustomer:(x:string)=>void}){return <><PageTitle title="Customers" copy="Revenue integrity across 146 active customer relationships."><button className="outline-btn"><Search size={14}/> Search customers</button></PageTitle><DataTable heads={["Customer","Billing model","Monthly revenue","Integrity score","Open findings","Last audited"]}>{findings.map((f,i)=><tr key={f.customer}><td><button className="customer-cell" onClick={()=>openCustomer(f.customer)}><Avatar f={f}/><b>{f.customer}</b></button></td><td>{["Subscription + usage","Enterprise commit","Per-seat","Annual platform","Usage tiered"][i%5]}</td><td>{money(32000+i*8700)}</td><td><span className="score-good">{f.confidence>90?`${f.confidence-2}%`:`${f.confidence}%`}</span></td><td>{i<4?1:2}</td><td>2 hours ago</td></tr>)}</DataTable></>}
function Contracts({openCustomer}:{openCustomer:(x:string)=>void}){const [selected,setSelected]=useState(0);return <><PageTitle title="Contracts" copy="AI-extracted commercial terms mapped to billing rules."><button className="outline-btn"><Upload size={14}/> Add contract</button></PageTitle><DataTable heads={["Customer","Contract value","Billing model","Renewal","Discount","Allowance","AI confidence"]}>{contracts.map((c,i)=><tr className={selected===i?"selected-row":""} onClick={()=>setSelected(i)} key={c.customer}><td><button className="customer-cell" onClick={()=>openCustomer(c.customer)}><i className="doc-icon"><FileText size={15}/></i><b>{c.customer}</b></button></td><td>{c.value}</td><td>{c.model}</td><td>{c.renewal}</td><td>{c.discount}</td><td>{c.allowance}</td><td><span className="score-good">{c.confidence}%</span></td></tr>)}</DataTable><div className="rule-compare"><div><span>ORIGINAL CONTRACT CLAUSE · PAGE 7</span><p>“Usage in excess of <mark>1,000,000 API requests</mark> per calendar month shall be billed at <mark>$0.0045 per additional request.</mark>”</p><button>Open source PDF <ArrowRight size={13}/></button></div><div><span>STRUCTURED BILLING RULE</span><pre><i>included_usage</i> = 1,000,000{"\n"}<i>metric</i> = api_requests{"\n"}<i>overage_price</i> = 0.0045{"\n"}<i>billing_period</i> = monthly</pre><small><Check size={12}/> Extracted with 99% confidence</small></div></div></>}
function Usage(){const data=[{d:"Sep 1",calls:116},{d:"Sep 6",calls:182},{d:"Sep 12",calls:244},{d:"Sep 18",calls:198},{d:"Sep 24",calls:310},{d:"Sep 30",calls:355}];return <><PageTitle title="Usage intelligence" copy="Normalized product telemetry mapped to customer entitlements."><select><option>All customers</option><option>Cortex Labs</option></select></PageTitle><div className="usage-metrics">{[["API calls","84.2M","+12.4%"],["Tokens","12.7B","+18.1%"],["Compute hours","48.3K","+4.2%"],["Active seats","3,842","+7.8%"],["Events","2.4B","+22.0%"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]} vs Aug</small></div>)}</div><ChartCard title="Metered consumption" subtitle="API calls · September 2026"><ResponsiveContainer width="100%" height={280}><AreaChart data={data}><defs><linearGradient id="usage" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#34d399" stopOpacity={.3}/><stop offset="1" stopColor="#34d399" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#22262d" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="calls" stroke="#34d399" fill="url(#usage)" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartCard><div className="exceed-card"><div><Zap size={17}/><span><b>12 customers exceeded contractual entitlements</b><small>4 missing corresponding overage charges</small></span></div><button>Review exceptions <ArrowRight size={13}/></button></div></>}
function Billing({openCustomer}:{openCustomer:(x:string)=>void}){return <><PageTitle title="Billing reconciliation" copy="Expected charges compared with actual invoice line items."><span className="sync"><i/> Stripe synced 8 min ago</span></PageTitle><DataTable heads={["Customer","Invoice","Period","Expected","Billed","Variance","Billing status"]}>{invoices.map(x=><tr key={x.invoice}><td><button className="customer-cell" onClick={()=>openCustomer(x.customer)}><b>{x.customer}</b></button></td><td><span className="mono">{x.invoice}</span></td><td>{x.period}</td><td>{money(x.expected)}</td><td>{money(x.billed)}</td><td className={x.flag?"leak-money":"muted"}>{x.flag?money(x.expected-x.billed):"—"}</td><td><span className={`table-status ${x.status.toLowerCase()}`}>{x.status}</span></td></tr>)}</DataTable></>}
function DataSources({openConnect}:{openConnect:()=>void}){const graphNodes:[React.ElementType,string,string][]=[[Building2,"CRM","Salesforce"],[FileText,"Contracts","146 documents"],[Activity,"Usage","2.4B events"],[Receipt,"Billing","3,842 line items"],[BadgeDollarSign,"Revenue ledger","$1.08M billed"]];return <><PageTitle title="Revenue data graph" copy="The evidence layer connecting every commercial promise to every charge."><button className="solid-btn" onClick={openConnect}><Zap size={14}/> Connect source</button></PageTitle><div className="data-graph">{graphNodes.map(([Icon,label,sub],i)=><div className="graph-node" key={label}><span><Icon size={21}/></span><b>{label}</b><small>{sub}</small>{i<4&&<i className="graph-line"><ChevronRight size={14}/></i>}</div>)}</div><h3 className="source-title">Connected integrations <span>9 sources</span></h3><div className="integration-grid">{["Stripe","Salesforce","HubSpot","Chargebee","Orb","Metronome","NetSuite","Warehouse","Contract PDFs"].map((x,i)=><div key={x}><span className={`int-icon int-${i}`}>{x.slice(0,1)}</span><p><b>{x}</b><small>{i<7?"Connected · Healthy":"Synced · 8 min ago"}</small></p><Check size={15}/></div>)}</div></>}
function ConnectModal({close}:{close:()=>void}){return <div className="modal-bg" onMouseDown={close}><div className="connect-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X/></button><span className="modal-icon"><Zap/></span><h2>Run RevLeak on your revenue stack</h2><p>Connect the systems that define what you promised, what customers used, and what you billed.</p><div className="connect-options">{["Connect Stripe","Connect Chargebee","Connect Salesforce","Connect HubSpot","Connect Orb","Connect Metronome","Upload contracts","Upload billing export","Connect data warehouse"].map((x,i)=><button key={x}><span>{["S","C","S","H","O","M","PDF","CSV","DB"][i]}</span>{x}<ChevronRight size={14}/></button>)}</div><div className="prototype-note"><ShieldCheck size={16}/><p><b>Prototype environment</b>Connections are simulated and no credentials or customer data will be collected.</p></div><button className="sample-btn" onClick={close}>Continue with sample company <ArrowRight size={14}/></button></div></div>}
